# Generated by Django 2.2.16 on 2022-09-13 10:23

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(db_index=True, max_length=256)),
                ('measurement_unit', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='IngredientReciepe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reciepes.Ingredient')),
            ],
        ),
        migrations.CreateModel(
            name='Reciepe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='reciepes/')),
                ('name', models.TextField(max_length=200)),
                ('text', models.TextField()),
                ('cooking_time', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('pub_date', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reciepes', to=settings.AUTH_USER_MODEL)),
                ('ingredients', models.ManyToManyField(through='reciepes.IngredientReciepe', to='reciepes.Ingredient')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(db_index=True, max_length=256, unique=True)),
                ('color', models.TextField(max_length=256, unique=True, validators=[django.core.validators.RegexValidator(message='mField must contain color HEX-code', regex='#?([\\da-fA-F]{2})([\\da-fA-F]{2})([\\da-fA-F]{2})')])),
                ('slug', models.CharField(max_length=50, unique=True, validators=[django.core.validators.RegexValidator(message='Unacceptable symbols', regex='^[-a-zA-Z0-9_]+$')])),
            ],
        ),
        migrations.CreateModel(
            name='TagReciepe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reciepe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reciepes.Reciepe')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reciepes.Tag')),
            ],
        ),
        migrations.CreateModel(
            name='Subscribe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follower', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Shoping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reciepe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reciepes.Reciepe')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='reciepe',
            name='tags',
            field=models.ManyToManyField(through='reciepes.TagReciepe', to='reciepes.Tag'),
        ),
        migrations.AddField(
            model_name='ingredientreciepe',
            name='reciepe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reciepes.Reciepe'),
        ),
        migrations.CreateModel(
            name='Favorited',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reciepe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reciepes.Reciepe')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='tagreciepe',
            constraint=models.UniqueConstraint(fields=('tag', 'reciepe'), name='unique_tag_reciepe'),
        ),
        migrations.AddConstraint(
            model_name='subscribe',
            constraint=models.UniqueConstraint(fields=('user', 'author'), name='subscription'),
        ),
        migrations.AddConstraint(
            model_name='shoping',
            constraint=models.UniqueConstraint(fields=('user', 'reciepe'), name='unique_shoping_reciepe'),
        ),
        migrations.AddConstraint(
            model_name='ingredientreciepe',
            constraint=models.UniqueConstraint(fields=('ingredient', 'reciepe'), name='unique_ingredient_reciepe'),
        ),
        migrations.AddConstraint(
            model_name='favorited',
            constraint=models.UniqueConstraint(fields=('user', 'reciepe'), name='unique_favorite_reciepe'),
        ),
    ]
