# Generated by Django 2.2.16 on 2022-09-12 17:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(db_index=True, max_length=256)),
                ('measurement_unit', models.TextField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(db_index=True, max_length=256, unique=True)),
                ('color', models.TextField(max_length=256, unique=True, validators=[django.core.validators.RegexValidator(message='Недопустимые символы', regex='#?([\\da-fA-F]{2})([\\da-fA-F]{2})([\\da-fA-F]{2})')])),
            ],
        ),
    ]
