# Generated by Django 2.2.16 on 2022-09-12 20:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reciepes', '0002_auto_20220912_1941'),
    ]

    operations = [
        migrations.AddField(
            model_name='reciepe',
            name='cooking_time',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
