# Generated by Django 2.2.16 on 2022-09-12 20:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reciepes', '0003_reciepe_cooking_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredientreciepe',
            name='amount',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
